name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: s3rgiosan/.github/.github/workflows/wp-plugin-release.yml@main
    with:
      slug: wp-theme-json-editor
